// Gerado por scripts/gerar_seed.py em 2026-06-10 — NÃO editar à mão; re-rode o script.
window.LIEBE_SEED = {
 "schema_version": 1,
 "seed_version": 1781100369,
 "generated_at": "2026-06-10",
 "users": [
  {
   "id": "user-joice",
   "name": "Joice",
   "job_title": "Coordenadora de Produto",
   "role": "admin",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-anna",
   "name": "Anna Karoline",
   "job_title": "Gerente de Estilo",
   "role": "equipe",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-thais",
   "name": "Thaís",
   "job_title": "Diretora de Estilo",
   "role": "equipe",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-adriana",
   "name": "Adriana",
   "job_title": "Modelista",
   "role": "equipe",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-silvana",
   "name": "Silvana",
   "job_title": "Pilotista Plena",
   "role": "equipe",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-safira",
   "name": "Safira",
   "job_title": "Pilotista",
   "role": "equipe",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-mariaclara",
   "name": "Maria Clara",
   "job_title": "Assistente de Estilo",
   "role": "equipe",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-israel",
   "name": "Israel",
   "job_title": "PCP",
   "role": "equipe",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-cairo",
   "name": "Cairo",
   "job_title": "Diretor Presidente",
   "role": "leitura",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-eugenia",
   "name": "Eugênia",
   "job_title": "Diretora Consultiva",
   "role": "leitura",
   "pin": "1234",
   "active": true
  },
  {
   "id": "user-vanderlei",
   "name": "Vanderlei (PWR)",
   "job_title": "Consultor PWR Gestão",
   "role": "admin",
   "pin": "1234",
   "active": true
  }
 ],
 "collections": [
  {
   "id": "col-inverno-alto-27",
   "name": "INVERNO & ALTO 27",
   "status": "em_andamento",
   "start_date": "2026-02-06",
   "end_date": "2026-12-20"
  },
  {
   "id": "col-inverno_27",
   "name": "INVERNO 27",
   "status": "em_andamento",
   "start_date": "2026-02-06",
   "end_date": "2026-12-20"
  },
  {
   "id": "col-inverno_28",
   "name": "INVERNO 28",
   "status": "em_andamento",
   "start_date": "2026-02-06",
   "end_date": "2026-12-20"
  },
  {
   "id": "col-verao_27",
   "name": "VERÃO 27",
   "status": "em_andamento",
   "start_date": "2026-02-06",
   "end_date": "2026-12-20"
  }
 ],
 "phases": [
  {
   "id": "phase-desenho",
   "key": "desenho",
   "name": "DESENHO",
   "seq": 1,
   "marco_owner": "anna",
   "flow_type": "nova"
  },
  {
   "id": "phase-modelagem",
   "key": "modelagem",
   "name": "MODELAGEM",
   "seq": 2,
   "marco_owner": "anna",
   "flow_type": "nova"
  },
  {
   "id": "phase-pilotagem",
   "key": "pilotagem",
   "name": "PILOTAGEM",
   "seq": 3,
   "marco_owner": "anna",
   "flow_type": "nova"
  },
  {
   "id": "phase-prova",
   "key": "prova",
   "name": "PROVA",
   "seq": 4,
   "marco_owner": "anna",
   "flow_type": "nova"
  },
  {
   "id": "phase-aprov_mod",
   "key": "aprov_mod",
   "name": "APROV. MOD.",
   "seq": 5,
   "marco_owner": "anna",
   "flow_type": "nova"
  },
  {
   "id": "phase-fluxo_operacional",
   "key": "fluxo_operacional",
   "name": "FLUXO OPERACIONAL",
   "seq": 6,
   "marco_owner": "joice",
   "flow_type": "nova"
  },
  {
   "id": "phase-comite",
   "key": "comite",
   "name": "COMITÊ",
   "seq": 7,
   "marco_owner": "joice",
   "flow_type": "nova"
  },
  {
   "id": "phase-cadastro",
   "key": "cadastro",
   "name": "CADASTRO",
   "seq": 8,
   "marco_owner": "joice",
   "flow_type": "nova"
  },
  {
   "id": "phase-pre_custo_aprovacao",
   "key": "pre_custo_aprovacao",
   "name": "PRÉ-CUSTO - APROVAÇÃO",
   "seq": 9,
   "marco_owner": "joice",
   "flow_type": "nova"
  },
  {
   "id": "phase-cadastro_de_cores_continuados",
   "key": "cadastro_de_cores_continuados",
   "name": "CADASTRO DE CORES (CONTINUADOS)",
   "seq": 10,
   "marco_owner": "joice",
   "flow_type": "continuado"
  },
  {
   "id": "phase-liberacao_para_pcp",
   "key": "liberacao_para_pcp",
   "name": "LIBERAÇÃO PARA PCP",
   "seq": 11,
   "marco_owner": "joice",
   "flow_type": "ambos"
  },
  {
   "id": "phase-pilotagem_grades",
   "key": "pilotagem_grades",
   "name": "PILOTAGEM GRADES",
   "seq": 12,
   "marco_owner": "anna",
   "flow_type": "nova"
  },
  {
   "id": "phase-prova_grades",
   "key": "prova_grades",
   "name": "PROVA GRADES",
   "seq": 13,
   "marco_owner": "anna",
   "flow_type": "nova"
  },
  {
   "id": "phase-aprovacao_grade",
   "key": "aprovacao_grade",
   "name": "APROVAÇÃO GRADE",
   "seq": 14,
   "marco_owner": "anna",
   "flow_type": "nova"
  },
  {
   "id": "phase-marcacao_de_fichas_de_medida",
   "key": "marcacao_de_fichas_de_medida",
   "name": "MARCAÇÃO DE FICHAS DE MEDIDA",
   "seq": 15,
   "marco_owner": "joice",
   "flow_type": "nova"
  },
  {
   "id": "phase-ficha_de_medidas",
   "key": "ficha_de_medidas",
   "name": "FICHA DE MEDIDAS",
   "seq": 16,
   "marco_owner": "joice",
   "flow_type": "nova"
  },
  {
   "id": "phase-digitacao_de_fichas",
   "key": "digitacao_de_fichas",
   "name": "DIGITAÇÃO DE FICHAS",
   "seq": 17,
   "marco_owner": "joice",
   "flow_type": "nova"
  },
  {
   "id": "phase-liberacao_de_peca_piloto",
   "key": "liberacao_de_peca_piloto",
   "name": "LIBERAÇÃO DE PEÇA PILOTO",
   "seq": 18,
   "marco_owner": "joice",
   "flow_type": "nova"
  },
  {
   "id": "phase-producao_de_peca_para_catalogo",
   "key": "producao_de_peca_para_catalogo",
   "name": "PRODUÇÃO DE PEÇA PARA CATÁLOGO",
   "seq": 19,
   "marco_owner": "joice",
   "flow_type": "ambos"
  }
 ],
 "phase_deadlines": [
  {
   "id": "dl-desenho",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-desenho",
   "deadline_date": "2026-03-16"
  },
  {
   "id": "dl-aprov_mod",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-aprov_mod",
   "deadline_date": "2026-04-16"
  },
  {
   "id": "dl-fluxo_operacional",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-fluxo_operacional",
   "deadline_date": "2026-04-16"
  },
  {
   "id": "dl-comite",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-comite",
   "deadline_date": "2026-03-16"
  },
  {
   "id": "dl-cadastro",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-cadastro",
   "deadline_date": "2026-04-01"
  },
  {
   "id": "dl-pre_custo_aprovacao",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-pre_custo_aprovacao",
   "deadline_date": "2026-05-08"
  },
  {
   "id": "dl-cadastro_de_cores_continuados",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-cadastro_de_cores_continuados",
   "deadline_date": "2026-05-18"
  },
  {
   "id": "dl-liberacao_para_pcp",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-liberacao_para_pcp",
   "deadline_date": "2026-05-28"
  },
  {
   "id": "dl-prova_grades",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-prova_grades",
   "deadline_date": "2025-09-19"
  },
  {
   "id": "dl-aprovacao_grade",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-aprovacao_grade",
   "deadline_date": "2026-05-29"
  },
  {
   "id": "dl-marcacao_de_fichas_de_medida",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-marcacao_de_fichas_de_medida",
   "deadline_date": "2026-06-08"
  },
  {
   "id": "dl-ficha_de_medidas",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-ficha_de_medidas",
   "deadline_date": "2026-06-04"
  },
  {
   "id": "dl-digitacao_de_fichas",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-digitacao_de_fichas",
   "deadline_date": "2026-06-05"
  },
  {
   "id": "dl-liberacao_de_peca_piloto",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-liberacao_de_peca_piloto",
   "deadline_date": "2026-05-13"
  },
  {
   "id": "dl-producao_de_peca_para_catalogo",
   "collection_id": "col-inverno-alto-27",
   "phase_id": "phase-producao_de_peca_para_catalogo",
   "deadline_date": "2026-06-30"
  }
 ],
 "macro_processes": [
  {
   "id": "proc-01",
   "collection_id": "col-inverno-alto-27",
   "seq": 1,
   "name": "Pesquisas inspiracionais",
   "owner_team": "Estilistas",
   "start_date": "2026-02-06",
   "end_date": "2026-02-25",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-02",
   "collection_id": "col-inverno-alto-27",
   "seq": 2,
   "name": "Escolha e solicitação da pilotagem de rendas e tecidos importados",
   "owner_team": "Estilistas",
   "start_date": "2026-02-13",
   "end_date": "2026-02-13",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-03",
   "collection_id": "col-inverno-alto-27",
   "seq": 3,
   "name": "Escolha de Cores exclusivas",
   "owner_team": "Estilistas",
   "start_date": "2026-02-26",
   "end_date": "2026-03-03",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-04",
   "collection_id": "col-inverno-alto-27",
   "seq": 4,
   "name": "Desenvolvimento de Cores exclusivas",
   "owner_team": "Assistente",
   "start_date": "2026-03-04",
   "end_date": "2026-03-27",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-05",
   "collection_id": "col-inverno-alto-27",
   "seq": 5,
   "name": "Reunião de Inteligência de mercado",
   "owner_team": "Assistente",
   "start_date": "2026-03-13",
   "end_date": "2026-03-13",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-06",
   "collection_id": "col-inverno-alto-27",
   "seq": 6,
   "name": "Atendimento a fornecedores",
   "owner_team": "Estilistas",
   "start_date": "2026-03-02",
   "end_date": "2026-03-16",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-07",
   "collection_id": "col-inverno-alto-27",
   "seq": 7,
   "name": "Solicitação de materiais novos para desenvolvimento",
   "owner_team": "Pilotagem",
   "start_date": "2026-03-02",
   "end_date": "2026-03-16",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-08",
   "collection_id": "col-inverno-alto-27",
   "seq": 8,
   "name": "Elaboração do planejamento de mix",
   "owner_team": "Supervisão",
   "start_date": "2026-03-06",
   "end_date": "2026-03-13",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-09",
   "collection_id": "col-inverno-alto-27",
   "seq": 9,
   "name": "Envio de amostras para desenvolvimento de Cores nos aviamentos",
   "owner_team": "Supervisão",
   "start_date": "2026-04-01",
   "end_date": "2026-04-08",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-10",
   "collection_id": "col-inverno-alto-27",
   "seq": 10,
   "name": "Reunião de Planejamento de coleção",
   "owner_team": "Assistente",
   "start_date": "2026-03-16",
   "end_date": "2026-03-16",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-11",
   "collection_id": "col-inverno-alto-27",
   "seq": 11,
   "name": "Chegada de novos materiais e informações técnicas para protótipos",
   "owner_team": "Supervisão",
   "start_date": "2026-02-26",
   "end_date": "2026-03-20",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-12",
   "collection_id": "col-inverno-alto-27",
   "seq": 12,
   "name": "Entrega de materiais novos para negociação de compras",
   "owner_team": "Assistente",
   "start_date": "2026-03-24",
   "end_date": "2026-04-16",
   "completed_at": null,
   "percent_complete": 17,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-13",
   "collection_id": "col-inverno-alto-27",
   "seq": 13,
   "name": "Entrega de materiais novo para testes de qualidade",
   "owner_team": "Assistente",
   "start_date": "2026-03-24",
   "end_date": "2026-04-16",
   "completed_at": null,
   "percent_complete": 17,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-14",
   "collection_id": "col-inverno-alto-27",
   "seq": 14,
   "name": "Pesquisas de modelos/tendências",
   "owner_team": "Pilotagem",
   "start_date": "2026-03-02",
   "end_date": "2026-03-16",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-15",
   "collection_id": "col-inverno-alto-27",
   "seq": 15,
   "name": "Desenho Técnico",
   "owner_team": "Gerente",
   "start_date": "2026-03-17",
   "end_date": "2026-04-01",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-16",
   "collection_id": "col-inverno-alto-27",
   "seq": 16,
   "name": "Modelagem do protótipo - (Até a aprovação)",
   "owner_team": "Pilotagem",
   "start_date": "2026-03-23",
   "end_date": "2026-05-08",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-17",
   "collection_id": "col-inverno-alto-27",
   "seq": 17,
   "name": "Fluxo operacional",
   "owner_team": "Assistente",
   "start_date": "2026-03-27",
   "end_date": "2026-05-13",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-18",
   "collection_id": "col-inverno-alto-27",
   "seq": 18,
   "name": "Comitê Operacional",
   "owner_team": "Modelagem",
   "start_date": "2026-04-02",
   "end_date": "2026-05-18",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-19",
   "collection_id": "col-inverno-alto-27",
   "seq": 19,
   "name": "Cadastro de referências",
   "owner_team": "Assistente",
   "start_date": "2026-04-29",
   "end_date": "2026-05-21",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-20",
   "collection_id": "col-inverno-alto-27",
   "seq": 20,
   "name": "Análise de preços e custos",
   "owner_team": "Estilistas",
   "start_date": "2026-05-04",
   "end_date": "2026-05-28",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-21",
   "collection_id": "col-inverno-alto-27",
   "seq": 21,
   "name": "Reunião estratégica (apresentação da coleção)",
   "owner_team": "Assistente",
   "start_date": "2026-05-29",
   "end_date": "2026-05-29",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-22",
   "collection_id": "col-inverno-alto-27",
   "seq": 22,
   "name": "Alterações comerciais (solicitadas na reunião estratégica)",
   "owner_team": "Pilotagem",
   "start_date": "2026-06-01",
   "end_date": "2026-06-08",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-23",
   "collection_id": "col-inverno-alto-27",
   "seq": 23,
   "name": "Cadastro de cores nas referências continuadas",
   "owner_team": "Modelagem",
   "start_date": "2026-06-01",
   "end_date": "2026-06-04",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-24",
   "collection_id": "col-inverno-alto-27",
   "seq": 24,
   "name": "Liberação da coleção para PCP",
   "owner_team": "Assistente",
   "start_date": "2026-06-05",
   "end_date": "2026-06-05",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-25",
   "collection_id": "col-inverno-alto-27",
   "seq": 25,
   "name": "Solicitação de materiais novos para produção de peças de fotos",
   "owner_team": "Assistente",
   "start_date": "2026-05-12",
   "end_date": "2026-05-13",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-26",
   "collection_id": "col-inverno-alto-27",
   "seq": 26,
   "name": "Organização de materiais a serem tingidos para peças de fotos",
   "owner_team": "Pilotagem",
   "start_date": "2026-06-23",
   "end_date": "2026-06-30",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-27",
   "collection_id": "col-inverno-alto-27",
   "seq": 27,
   "name": "Produção das grade de peças (até a aprovação)",
   "owner_team": "PCP",
   "start_date": "2026-05-11",
   "end_date": "2026-08-03",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-28",
   "collection_id": "col-inverno-alto-27",
   "seq": 28,
   "name": "Elaboração das fichas de medidas com desenho técnico atulaizado e marcações",
   "owner_team": "Estilistas",
   "start_date": "2026-07-20",
   "end_date": "2026-08-10",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-29",
   "collection_id": "col-inverno-alto-27",
   "seq": 29,
   "name": "Preenchimento das fichas de medidas",
   "owner_team": "Assistente",
   "start_date": "2026-07-21",
   "end_date": "2026-08-11",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-30",
   "collection_id": "col-inverno-alto-27",
   "seq": 30,
   "name": "Digitação de fichas físicas no drive",
   "owner_team": "Assistente",
   "start_date": "2026-08-07",
   "end_date": "2026-08-28",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-31",
   "collection_id": "col-inverno-alto-27",
   "seq": 31,
   "name": "Liberação de Peça Piloto para qualidade",
   "owner_team": "PCP",
   "start_date": "2026-08-31",
   "end_date": "2026-09-01",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-32",
   "collection_id": "col-inverno-alto-27",
   "seq": 32,
   "name": "Informações de tamanhos das modelos",
   "owner_team": null,
   "start_date": null,
   "end_date": "2026-07-24",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-33",
   "collection_id": "col-inverno-alto-27",
   "seq": 33,
   "name": "Chegada de materiais para peças de fotos",
   "owner_team": "Pilotagem",
   "start_date": null,
   "end_date": "2026-08-03",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-34",
   "collection_id": "col-inverno-alto-27",
   "seq": 34,
   "name": "ODD de peças com cores e tamanhos para fotos",
   "owner_team": null,
   "start_date": "2026-07-27",
   "end_date": "2026-08-03",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "proc-35",
   "collection_id": "col-inverno-alto-27",
   "seq": 35,
   "name": "Produção de peças para foto de catálogo",
   "owner_team": null,
   "start_date": "2026-08-04",
   "end_date": "2026-09-04",
   "completed_at": null,
   "percent_complete": 0,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  }
 ],
 "references": [
  {
   "id": "ref-001",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503151",
   "line": "FASHION",
   "family": "LE PETIT FLEUR",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-002",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503451",
   "line": "FASHION",
   "family": "LE PETIT FLEUR",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-003",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501751",
   "line": "FASHION",
   "family": "LE PETIT FLEUR",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-004",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501151",
   "line": "FASHION",
   "family": "LE PETIT FLEUR",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-005",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "506651",
   "line": "FASHION",
   "family": "LE PETIT FLEUR",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-006",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503352",
   "line": "FASHION",
   "family": "LUMINA",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-007",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503152",
   "line": "FASHION",
   "family": "LUMINA",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-008",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "703352",
   "line": "FASHION",
   "family": "LUMINA",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-009",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501252",
   "line": "FASHION",
   "family": "LUMINA",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-010",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501052",
   "line": "FASHION",
   "family": "LUMINA",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-011",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "701752",
   "line": "FASHION",
   "family": "LUMINA",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-012",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "506152",
   "line": "FASHION",
   "family": "LUMINA",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-013",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "504053",
   "line": "FASHION",
   "family": "MY LACE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-014",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503153",
   "line": "FASHION",
   "family": "MY LACE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-015",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503806",
   "line": "FASHION",
   "family": "MY LACE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-016",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501753",
   "line": "FASHION",
   "family": "MY LACE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-017",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501053",
   "line": "FASHION",
   "family": "MY LACE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-018",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503306",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-019",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "604088",
   "line": "LUXE",
   "family": "AFTER DARK",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-020",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603188",
   "line": "LUXE",
   "family": "AFTER DARK",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-021",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603488",
   "line": "LUXE",
   "family": "AFTER DARK",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-022",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601188",
   "line": "LUXE",
   "family": "AFTER DARK",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-023",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601788",
   "line": "LUXE",
   "family": "AFTER DARK",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-024",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601288",
   "line": "LUXE",
   "family": "AFTER DARK",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-025",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603387",
   "line": "LUXE",
   "family": "INNER FLAME",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-026",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603187",
   "line": "LUXE",
   "family": "INNER FLAME",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-027",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "604087",
   "line": "LUXE",
   "family": "INNER FLAME",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-028",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "703387",
   "line": "LUXE",
   "family": "INNER FLAME",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-029",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601187",
   "line": "LUXE",
   "family": "INNER FLAME",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-030",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601287",
   "line": "LUXE",
   "family": "INNER FLAME",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-031",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601787",
   "line": "LUXE",
   "family": "INNER FLAME",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-032",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "701787",
   "line": "LUXE",
   "family": "INNER FLAME",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-033",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603390",
   "line": "LUXE",
   "family": "GOLDEN PULSE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-034",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603190",
   "line": "LUXE",
   "family": "GOLDEN PULSE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-035",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601790",
   "line": "LUXE",
   "family": "GOLDEN PULSE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-036",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601290",
   "line": "LUXE",
   "family": "GOLDEN PULSE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-037",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603490",
   "line": "LUXE",
   "family": "GOLDEN PULSE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-038",
   "collection_id": "col-inverno_28",
   "collection_name": "INVERNO 28",
   "code": "606790",
   "line": "LUXE",
   "family": "GOLDEN PULSE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-039",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "302105",
   "line": "CONTROL",
   "family": "BÁSICOS",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-040",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136222",
   "line": "LOUNGEWEAR",
   "family": "VISCOW",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-041",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136122",
   "line": "LOUNGEWEAR",
   "family": "LACE",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-042",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "SUTIÃ TQC",
   "line": "IDEAL",
   "family": "BÁSICOS",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-043",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "SUTIÃ MTÇ",
   "line": "IDEAL",
   "family": "BÁSICOS",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-044",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "CALCINHA",
   "line": "IDEAL",
   "family": "BÁSICOS",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-045",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "CALCINHA",
   "line": "IDEAL",
   "family": "BÁSICOS",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-046",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "CALCINHA",
   "line": "IDEAL",
   "family": "BÁSICOS",
   "stylist": "ANNA KAROLINE",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-047",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603589",
   "line": "LUXE",
   "family": "NOIVAS",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-048",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603189",
   "line": "LUXE",
   "family": "NOIVAS",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-049",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601289",
   "line": "LUXE",
   "family": "NOIVAS",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-050",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601778",
   "line": "LUXE",
   "family": "NOIVAS",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-051",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "606189",
   "line": "LUXE",
   "family": "NOIVAS",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-052",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "606789",
   "line": "LUXE",
   "family": "NOIVAS",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-053",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603191",
   "line": "LUXE",
   "family": "LOVE APPEAL",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-054",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603091",
   "line": "LUXE",
   "family": "LOVE APPEAL",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-055",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "603391",
   "line": "LUXE",
   "family": "LOVE APPEAL",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-056",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601791",
   "line": "LUXE",
   "family": "LOVE APPEAL",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-057",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601291",
   "line": "LUXE",
   "family": "LOVE APPEAL",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-058",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "601271",
   "line": "LUXE",
   "family": "LOVE APPEAL",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-059",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "606691",
   "line": "LUXE",
   "family": "LOVE APPEAL",
   "stylist": "THAIS",
   "flow_type": "nova",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-060",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501723",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-061",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501742",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-062",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501745",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-063",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503303",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-064",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503503",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-065",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501602",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-066",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501701",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-067",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501715",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-068",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503001",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-069",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501003",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-070",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501302",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-071",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501000",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-072",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "503400",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-073",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "501700",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-074",
   "collection_id": "col-verao_27",
   "collection_name": "VERÃO 27",
   "code": "503303",
   "line": "FASHION",
   "family": "KISS ME",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-075",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "703402",
   "line": "FASHION",
   "family": "KISS ME T.M",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-076",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "703021",
   "line": "FASHION",
   "family": "KISS ME T.M",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-077",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "703302",
   "line": "FASHION",
   "family": "KISS ME T.M",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-078",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "701306",
   "line": "FASHION",
   "family": "KISS ME T.M",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-079",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "701708",
   "line": "FASHION",
   "family": "KISS ME T.M",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-080",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "701709",
   "line": "FASHION",
   "family": "KISS ME T.M",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-081",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "701502",
   "line": "FASHION",
   "family": "KISS ME T.M",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-082",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "106601",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-083",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "103101",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-084",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "103009",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-085",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "341001",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-086",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "103605",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-087",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "101700",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-088",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "201301",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-089",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "201702",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-090",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "101000",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-091",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "101500",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-092",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "101701",
   "line": "CONFORT",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-093",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "301701",
   "line": "FREE",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-094",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "301103",
   "line": "FREE",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-095",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "301705",
   "line": "FREE",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-096",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "306602",
   "line": "FREE",
   "family": "BÁSICOS",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-097",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136117",
   "line": "LOUNGEWEAR",
   "family": "VISCOW",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-098",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136219",
   "line": "LOUNGEWEAR",
   "family": "VISCOW",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-099",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136213",
   "line": "LOUNGEWEAR",
   "family": "VISCOW",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-100",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136113",
   "line": "LOUNGEWEAR",
   "family": "VISCOW",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-101",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136112",
   "line": "LOUNGEWEAR",
   "family": "VISCOW",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-102",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136118",
   "line": "LOUNGEWEAR",
   "family": "VISCOW",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-103",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136218",
   "line": "LOUNGEWEAR",
   "family": "VISCOW",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-104",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136910",
   "line": "LOUNGEWEAR",
   "family": "CETIM",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-105",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136221",
   "line": "LOUNGEWEAR",
   "family": "CETIM",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-106",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136121",
   "line": "LOUNGEWEAR",
   "family": "CETIM",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-107",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136109",
   "line": "LOUNGEWEAR",
   "family": "LACE",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-108",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136209",
   "line": "LOUNGEWEAR",
   "family": "LACE",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-109",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136119",
   "line": "LOUNGEWEAR",
   "family": "LACE",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-110",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136120",
   "line": "LOUNGEWEAR",
   "family": "NOIR",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-111",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136220",
   "line": "LOUNGEWEAR",
   "family": "NOIR",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-112",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136200",
   "line": "LOUNGEWEAR",
   "family": "NOIR",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-113",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "136110",
   "line": "LOUNGEWEAR",
   "family": "NOIR",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "ref-114",
   "collection_id": "col-inverno_27",
   "collection_name": "INVERNO 27",
   "code": "605366",
   "line": "LUXE",
   "family": "LOVE APPEAL",
   "stylist": "CONTINUADA",
   "flow_type": "continuado",
   "notes": null,
   "active": true,
   "status": "ativa",
   "canceled_at": null,
   "canceled_by": null,
   "cancel_category": null,
   "cancel_reason": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  }
 ],
 "reference_phases": [
  {
   "id": "rp-017-modelagem",
   "reference_id": "ref-017",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-04-11",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-017-pilotagem",
   "reference_id": "ref-017",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-05",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-017-prova",
   "reference_id": "ref-017",
   "phase_id": "phase-prova",
   "completed_at": "2026-05-19",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-017-aprov_mod",
   "reference_id": "ref-017",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-017-fluxo_operacional",
   "reference_id": "ref-017",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-06-01",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-019-modelagem",
   "reference_id": "ref-019",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-04-04",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-019-pilotagem",
   "reference_id": "ref-019",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-27",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-019-prova",
   "reference_id": "ref-019",
   "phase_id": "phase-prova",
   "completed_at": "2026-05-25",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-019-aprov_mod",
   "reference_id": "ref-019",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-019-fluxo_operacional",
   "reference_id": "ref-019",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-05-28",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-023-modelagem",
   "reference_id": "ref-023",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-05-18",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-023-pilotagem",
   "reference_id": "ref-023",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-20",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-023-prova",
   "reference_id": "ref-023",
   "phase_id": "phase-prova",
   "completed_at": "2026-05-25",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-023-aprov_mod",
   "reference_id": "ref-023",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-023-fluxo_operacional",
   "reference_id": "ref-023",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-05-27",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-024-modelagem",
   "reference_id": "ref-024",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-04-07",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-024-pilotagem",
   "reference_id": "ref-024",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-20",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-024-prova",
   "reference_id": "ref-024",
   "phase_id": "phase-prova",
   "completed_at": "2026-05-25",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-024-aprov_mod",
   "reference_id": "ref-024",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-024-fluxo_operacional",
   "reference_id": "ref-024",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-05-27",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-034-modelagem",
   "reference_id": "ref-034",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-04-15",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-034-pilotagem",
   "reference_id": "ref-034",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-15",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-034-prova",
   "reference_id": "ref-034",
   "phase_id": "phase-prova",
   "completed_at": "2026-05-19",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-034-aprov_mod",
   "reference_id": "ref-034",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-034-fluxo_operacional",
   "reference_id": "ref-034",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-06-01",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-036-modelagem",
   "reference_id": "ref-036",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-04-15",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-036-pilotagem",
   "reference_id": "ref-036",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-15",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-036-prova",
   "reference_id": "ref-036",
   "phase_id": "phase-prova",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-036-aprov_mod",
   "reference_id": "ref-036",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-036-fluxo_operacional",
   "reference_id": "ref-036",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-06-01",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-040-modelagem",
   "reference_id": "ref-040",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-04-15",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-040-pilotagem",
   "reference_id": "ref-040",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-06",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-040-prova",
   "reference_id": "ref-040",
   "phase_id": "phase-prova",
   "completed_at": "2026-05-19",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-040-aprov_mod",
   "reference_id": "ref-040",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-040-fluxo_operacional",
   "reference_id": "ref-040",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-05-26",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-050-modelagem",
   "reference_id": "ref-050",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-04-04",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-050-pilotagem",
   "reference_id": "ref-050",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-13",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-050-prova",
   "reference_id": "ref-050",
   "phase_id": "phase-prova",
   "completed_at": "2026-05-18",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-050-aprov_mod",
   "reference_id": "ref-050",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-05-27",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-050-fluxo_operacional",
   "reference_id": "ref-050",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-05-25",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-054-modelagem",
   "reference_id": "ref-054",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-04-16",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-054-pilotagem",
   "reference_id": "ref-054",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-19",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-054-prova",
   "reference_id": "ref-054",
   "phase_id": "phase-prova",
   "completed_at": "2026-05-21",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-054-aprov_mod",
   "reference_id": "ref-054",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-054-fluxo_operacional",
   "reference_id": "ref-054",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-05-28",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-056-modelagem",
   "reference_id": "ref-056",
   "phase_id": "phase-modelagem",
   "completed_at": "2026-04-15",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-056-pilotagem",
   "reference_id": "ref-056",
   "phase_id": "phase-pilotagem",
   "completed_at": "2026-05-12",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-056-prova",
   "reference_id": "ref-056",
   "phase_id": "phase-prova",
   "completed_at": "2026-05-18",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-056-aprov_mod",
   "reference_id": "ref-056",
   "phase_id": "phase-aprov_mod",
   "completed_at": "2026-06-02",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  },
  {
   "id": "rp-056-fluxo_operacional",
   "reference_id": "ref-056",
   "phase_id": "phase-fluxo_operacional",
   "completed_at": "2026-05-25",
   "completed_by": "user-joice",
   "notes": null,
   "created_at": "2026-06-10",
   "created_by": "user-vanderlei"
  }
 ],
 "reference_log": [],
 "tasks": [],
 "rituals": [],
 "charges": [],
 "kpi_entries": [],
 "bypass_log": []
};
